Formula/tcld.rb
update tcld to v0.1.2
gets latest changes
=> update tcld to v0.1.2

Formula/tcld.rb
=> upgrade tcld to v0.1.3

Formula/tcld.rb
update tcld release version to v0.5.0
see https://github.com/temporalio/tcld/releases/tag/v0.5.0
=> update tcld release version to v0.5.0

Formula/tcld.rb
update sha256 of v0.5.0 to slightly newer build
update sha256 of v0.5.0
see: https://github.com/temporalio/tcld/releases/tag/v0.5.0
=> update sha256 of v0.5.0

Formula/tcld.rb
bump tcld version to 0.6.0
see https://github.com/temporalio/tcld/releases/tag/v0.6.0
=> bump tcld version to 0.6.0

Formula/tcld.rb
see: https://github.com/temporalio/tcld/releases/tag/v0.7.0
=> Update tcld.rb to 0.7.0

Formula/tcld.rb
see: https://github.com/temporalio/tcld/releases/tag/v0.9.0
=> Update tcld.rb to 0.9.0

Formula/tcld.rb
=> update tcld to 0.10.0

Formula/tcld.rb
https://github.com/temporalio/tcld/releases/tag/v0.11.0
1. Closes 
=> update tcld to v0.12.0

Formula/tcld.rb
=> Upgrade tcld to v0.13.0

Formula/tcld.rb
=> bump tcld version

Formula/tcld.rb
❯ brew install --build-from-source Formula/tcld.rb
❯ brew test Formula/tcld.rb
==> Testing tcld
==> /opt/homebrew/Cellar/tcld/0.17.0/bin/tcld version 2>&1
==> /opt/homebrew/Cellar/tcld/0.17.0/bin/tcld help
➜  homebrew-brew git:(main) ✗ 
1. Closes 
=> Bump tcld to v0.17.0

Formula/tcld.rb
=> revert the latest tcld change

Formula/tcld.rb
=> release homebrew to point to v0.17.0

Formula/tcld.rb
Update tcld to [v0.18.0](https://github.com/temporalio/tcld/releases/tag/v0.18.0).
To prepare for service accounts private preview.
1. Closes 
=> Update to tcld v0.18.0

Formula/tcld.rb
https://github.com/temporalio/tcld/releases
1. Closes 
=> release tcld v0.19.0

Formula/tcld.rb
Updates tcld to [v0.21.0](https://github.com/temporalio/tcld/releases/tag/v0.21.0).
1. Closes 
=> Update to tcld v0.21.0

Formula/tcld.rb
https://github.com/temporalio/tcld/releases/tag/v0.29.0
1. Closes 
=> release v0.29.0

Formula/tcld.rb
https://github.com/temporalio/tcld/releases/tag/v0.30.0
1. Closes 
=> release v0.30.0

Formula/tcld.rb
Bump tcld to v0.38.0
Progress waits for no one. 
1. Closes  N/A
```
❯ brew install --build-from-source Formula/tcld.rb
❯ brew test Formula/tcld.rb
```
3. Any docs updates needed? N/A
=> chore: update tcld version

Formula/tcld.rb
=> chore: bump tcld to v0.39.0

Formula/tcld.rb
=> Bump tcld to 0.43.0

Formula/tcld.rb
=> Bump tcld to v0.44.0
